### PR TITLE
Add a check which verifies pack contains config.schema.yaml and not config.yaml

### PR DESCRIPTION
**Pull request by Kami**
This pull request adds a CI check for each pack which verifies pack contains `config.schema.yaml` file and no `config.yaml` file.

Note: This should only be merged once we update all the existing packs and make sure they all have `config.schema.yaml`.

### CODE REVIEW

**Comment by LindsayHill** [comment]
👍 Looks good, but as you say, wait until we finish the list here before merging https://github.com/StackStorm/st2/issues/3424#issuecomment-302774214

**Comment by LindsayHill** [comment]
All Exchange packs have now been updated.

But thinking a bit more about this, what about packs that don't have (or need) a `config.schema.yaml`file? e.g. github.com/StackStorm-Exchange/stackstorm-urbandict

Those should not fail validation because they do not contain a config.schema.yaml. They would fail validation if they had an empty config.schema.

**Comment by Kami** [comment]
@LindsayHill Perhaps the easiest way would be to add empty config schema to those packs?

Since we have more packs with config schema than without so I think having a check which checks pack contains a schema is not a bad idea (alternative would be to not have this check at all).

**Comment by LindsayHill** [comment]
Wasn’t there an issue at one stage with having an empty config.schema file? Can’t remember the details, might need to check that. 

But anyway, in general I think that’s an Ok approach. Might also need to update docs to say ‘you must have this file (even if it’s empty)’

**Comment by LindsayHill** [comment]
I don't think this is required anymore. Recent versions now throw ERROR if a pack contains `config.yaml`:

```shell
2018-06-13 16:12:26,666 ERROR [-] Pack "st2" contains a deprecated config.yaml file (/opt/stackstorm/packs/st2/config.yaml). Support for "config.yaml" files has been deprecated in StackStorm v1.6.0 in favor of config.schema.yaml config schema files and config files in /opt/stackstorm/configs/ directory. Support for config.yaml files has been removed in the release (v2.4.0) so please migrate. For more information please refer to https://docs.stackstorm.com/reference/pack_configs.html
```

**Pull request closed without merging**
