### PR TITLE
Bump pyyaml version

### PR DESCRIPTION
**Pull request by LindsayHill**

### CODE REVIEW

**Comment by Kami** [comment]
Pushes a small change (b824c67) which shouldn't be needed with this upgrade anymore, but still.

**Comment by LindsayHill** [comment]
Ta

**Comment by LindsayHill** [comment]
@Kami looks like https://github.com/StackStorm-Exchange/ci/commit/b824c6761dea90e14bfdc1ee35d81979d7c9529c causes problems - see https://circleci.com/gh/StackStorm-Exchange/stackstorm-icinga2/61

I'll leave that to you to decide how you want to fix it

**Comment by Kami** [comment]
Sorry about that - I simply reverted that change.

With new version of pyyaml ``load`` now works as ``safe_load`` so we should be fine.

**Pull request merged**
